### ISSUE TITLE
How to Serialize the Icons, or Provide Store for Icons?

### ISSUE THREAD

**Issue by GiteeBoy** [vitali-fedulov/images3#2]
For large set of images, the cached icons is very useful for repeated querying.

Just like the `Store` of https://github.com/rivo/duplo

**Comment by vitali-fedulov** [comment]
Your question seems to relate to general Golang serialization. Is that correct?

For that I would use Golang gob: https://pkg.go.dev/encoding/gob

I intentionally do not provide any store, as there are great solutions by other developers.

Please correct me, or close the issue, if not relevant anymore.

**Comment by vitali-fedulov** [comment]
Could you share an example code with the gob implementation? So I better understand what you are trying to achieve.
